import ReactMarkdown from 'react-markdown'
import { useContext } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import { css } from '@emotion/css'
import { ethers } from 'ethers'
import { AccountContext } from '../../context'
import { contractAddress, ownerAddress } from '../../config'
import Blog from '../../artifacts/contracts/Blog.sol/Blog.json'

